function field_meaning = get_network_field_meanings(data_type, submodule)
% GET_NETWORK_FIELD_MEANINGS - 获取网络构建模块字段的中文含义映射
% 此函数专门为 network_build 模块设计
%
% 输入参数:
%   data_type: 数据类型，可选 'input_params', 'calc_process', 'calc_result'
%   submodule: （仅当data_type='calc_process'时有效）子模块名称
%              可选 'network_construction_core', 'edge_processing_module', 'network_statistics_calculator'
%
% 输出参数:
%   field_meaning: 字段映射的结构体
    try
        switch data_type
            case 'input_params'
                field_meaning = struct(...
                    'analysis_type',           '分析方法', ...
                    'alpha',                   '显著性水平', ...
                    'corr_method',             '相关性方法', ...
                    'min_obs',                 '最小观测数', ...
                    'time_period',             '时间周期', ...
                    'stock_list',              '股票列表', ...
                    'param_info',              '参数配置信息', ...
                    'pairwise_results',        '配对结果数据', ...
                    'pair_info',               '配对信息元胞数组', ...
                    'connectivity',            '连接强度元胞数组', ...
                    'significance',            '显著性P值元胞数组', ...
                    'lag_info',                '滞后信息元胞数组', ...
                    'robustness',              '稳健性测试元胞数组', ...
                    'robustness_score',        '稳健性得分数组', ...
                    'is_robust',               '是否稳健标志数组', ...
                    'fingerprint_features',    '指纹特征元胞数组', ...
                    'parameters',              '参数结构体', ...
                    'pair_count',              '配对数', ...
                    'node_count',              '节点数', ...
                    'connectivity_threshold',  '连接强度阈值', ...
                    'lag_order',               '滞后阶数', ...
                    'granger_lag',             '格兰杰滞后阶数', ...
                    'granger_alpha',           '格兰杰检验显著性水平', ...
                    'data_frequency',          '数据频率', ...
                    'data_length',             '数据长度', ...
                    'start_date',              '开始日期', ...
                    'end_date',                 '结束日期', ...
                    'max_lag',                 '最大滞后阶数', ...
                    'bootstrap_reps',          'bootstrap重复次数', ...
                    'verbose',                 '详细输出', ...
                    'enable_robustness',       '启用稳健性检验', ...
                    'robustness_n_bootstrap',  '稳健性bootstrap次数', ...
                    'robustness_noise_level',  '稳健性噪声水平', ...
                    'robustness_threshold',    '稳健性阈值', ...
                    'enable_nonlinear_test',   '启用非线性检验', ...
                    'bds_m',                   'BDS检验m参数', ...
                    'bds_epsilon',             'BDS检验epsilon参数', ...
                    'pair_labels',             '配对标签列表', ...
                    'processing_stats',        '处理统计信息', ...
                    'total_pairs',             '总配对数', ...
                    'processed_pairs',         '已处理配对数', ...
                    'skipped_pairs',           '跳过的配对数', ...
                    'successful_pairs',        '成功配对数', ...
                    'failed_pairs',            '失败配对数', ...
                    'submodule_stats',         '子模块统计', ...
                    'start_time',              '开始时间', ...
                    'computation_time',        '计算时间', ...
                    'timestamp',               '时间戳', ...
                    'version',                 '版本信息' ...
                );

            case 'calc_process'
                % 如果指定了子模块，返回对应子模块的映射
                if nargin < 2
                    error('calc_process需要指定子模块名称: network_construction_core, edge_processing_module, network_statistics_calculator');
                end

                switch submodule
                    case 'network_construction_core'
                        field_meaning = get_network_construction_core_mapping();

                    case 'edge_processing_module'
                        field_meaning = get_edge_processing_mapping();

                    case 'network_statistics_calculator'
                        field_meaning = get_network_statistics_mapping();

                    otherwise
                        error('未知的子模块: %s。可用子模块: network_construction_core, edge_processing_module, network_statistics_calculator', submodule);
                end

            case 'calc_result'
                field_meaning = struct(...
                    'network_id',        '网络标识符', ...
                    'analysis_type',     '分析类型', ...
                    'alpha',             '显著性水平', ...
                    'n_nodes',           '节点总数', ...
                    'n_edges',           '边总数', ...
                    'density',           '网络密度', ...
                    'clustering_coefficient', '聚类系数', ...
                    'average_path_length', '平均路径长度', ...
                    'diameter',          '网络直径', ...
                    'is_directed',       '是否为有向网络', ...
                    'is_weighted',       '是否为加权网络', ...
                    'graph_type',        '图类型', ...
                    'version',           '版本信息', ...
                    'creation_time',     '创建时间', ...
                    'node_labels',       '节点标签', ...
                    'ret_node_labels',   '收益率序列节点标签', ...
                    'obv_node_labels',   'OBV指标节点标签', ...
                    'adjacency',         '邻接矩阵', ...
                    'weights',           '权重矩阵', ...
                    'significance',      '显著性矩阵', ...
                    'directions',        '连接方向矩阵', ...
                    'lags',              '滞后矩阵', ...
                    'edge_list',         '边列表', ...
                    'n_edges_in_list',  '边列表边数', ...
                    'node_degrees',      '节点度数', ...
                    'weighted_degrees',  '加权节点度数', ...
                    'degree_centrality', '度中心性', ...
                    'closeness_centrality', '接近中心性', ...
                    'betweenness_centrality', '介数中心性', ...
                    'eigenvector_centrality', '特征向量中心性', ...
                    'clustering_coefficients', '聚类系数', ...
                    'node_betweenness',  '节点介数中心性', ...
                    'node_closeness',    '节点接近中心性', ...
                    'modularity',        '模块度', ...
                    'assortativity',     '同配性', ...
                    'small_worldness',   '小世界性', ...
                    'degree_stats',       '度统计', ...
                    'min_degree',         '最小度数', ...
                    'max_degree',         '最大度数', ...
                    'mean_degree',        '平均度数', ...
                    'std_degree',         '度数标准差', ...
                    'median_degree',      '度数中位数', ...
                    'mode_degree',        '度数众数', ...
                    'skewness_degree',    '度数偏度', ...
                    'kurtosis_degree',    '度数峰度', ...
                    'weighted_degree_stats', '加权度统计', ...
                    'min_weighted_degree', '最小加权度数', ...
                    'max_weighted_degree', '最大加权度数', ...
                    'mean_weighted_degree', '平均加权度数', ...
                    'std_weighted_degree',  '加权度数标准差', ...
                    'median_weighted_degree', '加权度数中位数', ...
                    'processing_stats',  '处理统计信息', ...
                    'total_pairs',       '总配对数', ...
                    'processed_pairs',   '已处理配对数', ...
                    'edges_added',       '添加的边数', ...
                    'errors',           '错误数', ...
                    'processing_time_seconds', '处理时间(秒)', ...
                    'pairs_per_second', '处理速度(对/秒)', ...
                    'success_rate',     '成功率', ...
                    'weight_overrides', '权重覆盖数', ...
                    'param_info',        '参数信息', ...
                    'timestamps',        '时间戳', ...
                    'construction_start', '构建开始时间', ...
                    'construction_end',   '构建结束时间', ...
                    'total_computation_seconds', '总计算时间(秒)', ...
                    'validation_summary', '验证摘要', ...
                    'timestamp',         '时间戳', ...
                    'network_type',      '网络类型', ...
                    'computed_edges',    '计算的边数', ...
                    'max_possible_edges', '最大可能边数', ...
                    'edge_ratio',        '边数比例', ...
                    'is_connected',      '是否连通', ...
                    'has_self_loops',    '是否有自环', ...
                    'validation_passed', '验证是否通过', ...
                    'validation_errors',  '验证错误' ...
                );

            otherwise
                field_meaning = struct();
        end
    catch ME
        fprintf('网络构建字段映射 失败: %s\n', ME.message);
    end
end

%% 网络构建核心模块映射
function mapping = get_network_construction_core_mapping()
% GET_NETWORK_CONSTRUCTION_CORE_MAPPING - 返回 network_construction_core 的完整字段映射

    mapping = struct(...
        'module_name',              '模块名称', ...
        'version',                  '版本', ...
        'timestamp',                '时间戳', ...
        'start_time_tic',           '开始时间(tic)', ...
        'total_execution_time',     '总执行时间', ...
        'module_info_start_time',   '开始时间', ...
        'module_info_end_time',     '结束时间', ...
        'module_info_analysis_type', '分析类型', ...
        'module_info_significance_level', '显著性水平', ...
        'module_info_computation_time', '计算时间', ...
        'timings_validation_start', '验证开始时间', ...
        'timings_validation_end',   '验证结束时间', ...
        'timings_extraction_start', '提取开始时间', ...
        'timings_extraction_end',   '提取结束时间', ...
        'timings_processing_start', '处理开始时间', ...
        'timings_processing_end',   '处理结束时间', ...
        'timings_mapping_start',    '映射开始时间', ...
        'timings_mapping_end',      '映射结束时间', ...
        'timings_matrix_start',     '矩阵初始化开始时间', ...
        'timings_matrix_end',       '矩阵初始化结束时间', ...
        'timings_assembly_start',   '网络组装开始时间', ...
        'timings_assembly_end',     '网络组装结束时间', ...
        'timings_total_duration',   '总持续时间', ...
        'timings_stage_breakdown',  '阶段时间明细', ...
        'stage_breakdown_validation_time', '验证阶段耗时', ...
        'stage_breakdown_extraction_time', '提取阶段耗时', ...
        'stage_breakdown_processing_time', '处理阶段耗时', ...
        'stage_breakdown_mapping_time',   '映射阶段耗时', ...
        'stage_breakdown_matrix_init_time', '矩阵初始化耗时', ...
        'stage_breakdown_assembly_time',  '网络组装耗时', ...
        'stage_breakdown_total_time',     '阶段总计耗时', ...
        'validation_n_pairs',       '配对数', ...
        'validation_max_lag',       '最大滞后阶数', ...
        'validation_significance_threshold', '显著性阈值', ...
        'validation_conn_threshold', '连接强度阈值', ...
        'validation_input_valid',   '输入有效性', ...
        'validation_message',       '验证消息', ...
        'validation_input_checksum', '输入校验和', ...
        'extraction_unique_nodes',  '唯一节点列表', ...
        'extraction_n_unique_nodes', '唯一节点数', ...
        'extraction_node_mapping',  '节点映射', ...
        'extraction_stock_list',    '股票列表', ...
        'processing_original_nodes', '原始节点', ...
        'processing_filtered_nodes', '过滤后节点', ...
        'processing_duplicates_removed', '移除的重复节点', ...
        'processing_final_nodes',   '最终节点', ...
        'mapping_ret_nodes',        '收益节点', ...
        'mapping_obv_nodes',        'OBV节点', ...
        'mapping_node_index_map',   '节点索引映射', ...
        'mapping_ret_node_indices', '收益节点索引', ...
        'mapping_obv_node_indices', 'OBV节点索引', ...
        'matrix_init_n_nodes',      '节点总数', ...
        'matrix_init_matrix_dimensions', '矩阵维度', ...
        'matrix_init_total_elements', '总元素数', ...
        'matrix_init_estimated_memory_mb', '估算内存(MB)', ...
        'matrix_init_matrices_initialized', '已初始化矩阵', ...
        'performance_pairs_per_second', '配对处理速度(对/秒)', ...
        'performance_nodes_per_second', '节点处理速度(节点/秒)', ...
        'performance_memory_per_node_mb', '每节点内存(MB/节点)', ...
        'summary_total_pairs_processed', '总处理配对数', ...
        'summary_total_nodes_found', '总发现节点数', ...
        'summary_successful_mappings', '成功映射数', ...
        'summary_overall_status',   '总体状态', ...
        'elapsed_time',             '运行时间', ...
        'memory_usage_mb',         '内存使用量(MB)', ...
        'status',                   '运行状态', ...
        'error_message',            '错误消息', ...
        'warning_count',            '警告数量', ...
        'error_count',              '错误数量', ...
        'progress_percent',         '进度百分比', ...
        'current_stage',            '当前阶段', ...
        'stage_progress',           '阶段进度' ...
    );
end

%% 边处理模块映射
function mapping = get_edge_processing_mapping()
% GET_EDGE_PROCESSING_MAPPING - 返回 edge_processing_module 的完整字段映射
% 此映射基于处理统计结构体中的所有可能字段
    try
        mapping = struct(...
            'module_metadata_module_name', '模块名称', ...                  % 模块元信息 (module_metadata)
            'module_metadata_version', '版本', ... 
            'module_metadata_timestamp', '时间戳', ...
            'module_metadata_analysis_type', '分析类型', ...
            'module_metadata_significance_level', '显著性水平', ...
            'module_metadata_min_correlation_threshold', '最小相关系数阈值', ...
            'module_metadata_log_enabled', '日志启用状态', ...
            'module_metadata_log_level', '日志级别', ...
            'module_metadata_keep_calc_records', '计算记录保留状态', ...
            'module_metadata_computation_id', '计算标识符', ...
            'parameters_n_pairs', '配对数', ...                             % 输入参数配置 (parameters) ====================
            'parameters_n_nodes', '节点数', ...
            'parameters_analysis_type', '分析方法', ...
            'parameters_alpha', '显著性水平', ...
            'parameters_min_corr', '最小相关系数阈值', ...
            'parameters_node_labels_count', '节点标签数', ...
            'parameters_adjacency_initial_edges', '初始邻接矩阵边数', ...
            'parameters_weight_initial_nonzero', '初始权重矩阵非零元素数', ...
            'performance_total_time', '总处理时间', ...                     % 性能统计 (performance) ====================
            'performance_pairs_per_second', '处理速度(对/秒)', ...
            'performance_edges_per_second', '边处理速度(边/秒)', ...
            'performance_validation_avg', '验证阶段平均耗时', ...
            'performance_extraction_avg', '提取阶段平均耗时', ...
            'performance_decision_avg', '决策阶段平均耗时', ...
            'performance_update_avg', '更新阶段平均耗时', ...
            'performance_total_pair_avg', '配对处理平均总耗时', ...
            'summary_stats_total_pairs', '总配对数', ...                    % 摘要统计 (summary_stats) ====================
            'summary_stats_processed_pairs', '已处理配对数', ...
            'summary_stats_skipped_pairs', '跳过配对数', ...
            'summary_stats_added_edges', '添加边总数', ...
            'summary_stats_correlation_edges', '相关性边数量', ...
            'summary_stats_granger_edges', 'Granger因果边数量', ...
            'summary_stats_bidirectional_edges', '双向边数量', ...
            'summary_stats_unidirectional_edges', '单向边数量', ...
            'summary_stats_no_connectivity_results', '无连通性结果数', ...
            'summary_stats_invalid_pair_info', '无效配对信息数', ...
            'summary_stats_nodes_not_found', '节点未找到数', ...
            'summary_stats_weight_overrides', '权重覆盖次数', ...
            'summary_stats_weight_conflicts_recorded', '记录的权重冲突数', ...
            'summary_stats_weight_conflicts_resolved', '已解决的权重冲突数', ...
            'summary_stats_density_before', '处理前网络密度', ...
            'summary_stats_density_after', '处理后网络密度', ...
            'summary_stats_calc_records_created', '创建的计算记录数', ...
            'summary_stats_calc_records_saved', '保存的计算记录数', ...
            'summary_stats_calc_records_processed', '处理的计算记录数', ...
            'detailed_calculation_pair_records', '配对详细记录数组', ...     % 详细计算记录（可选，当前为空） ====================
            'detailed_calculation_stage_summaries', '阶段摘要', ...
            'detailed_calculation_conflict_records', '冲突记录', ...
            'detailed_calculation_matrix_updates', '矩阵更新记录' ... 
        );
        
        % 记录创建的字段数量
%        field_count = length(fieldnames(mapping));
%        fprintf('边处理模块字段映射创建完成，共 %d 个字段\n', field_count);
        
    catch ME
        % 捕获并报告错误
        fprintf('边处理模块映射创建出错: %s\n', ME.message);
        fprintf('错误发生在文件: %s, 行号: %d\n', ME.stack(1).name, ME.stack(1).line);
        
        % 创建空映射，避免程序崩溃
        mapping = struct();
    end
end

%% 网络统计计算器映射
function mapping = get_network_statistics_mapping()
    mapping = struct(...
        'module_name',                  '网络统计模块名称', ...
        'timestamp',                    '时间戳', ...
        'analysis_type',                '分析类型', ...
        'network_size',                 '网络规模', ...
        'basic_statistics',             '基本统计', ...
        'n_nodes',                      '节点数', ...
        'n_edges',                      '边数', ...
        'density',                      '密度', ...
        'is_directed',                  '是否有向', ...
        'is_weighted',                   '是否加权', ...
        'is_connected',                 '是否连通', ...
        'connected_components',         '连通分量数', ...
        'largest_component_size',      '最大连通分量大小', ...
        'degree_statistics',            '度统计', ...
        'degree_distribution',          '度分布', ...
        'in_degree_distribution',       '入度分布', ...
        'out_degree_distribution',      '出度分布', ...
        'mean_degree',                  '平均度数', ...
        'std_degree',                   '度数标准差', ...
        'max_degree',                   '最大度数', ...
        'min_degree',                   '最小度数', ...
        'degree_skewness',              '度数偏度', ...
        'degree_kurtosis',              '度数峰度', ...
        'centrality_statistics',        '中心性统计', ...
        'degree_centrality',            '度中心性', ...
        'closeness_centrality',         '接近中心性', ...
        'betweenness_centrality',       '介数中心性', ...
        'eigenvector_centrality',      '特征向量中心性', ...
        'pagerank_centrality',          'PageRank中心性', ...
        'top_central_nodes',            '中心性最高节点', ...
        'centrality_distribution',      '中心性分布', ...
        'clustering_statistics',        '聚类统计', ...
        'global_clustering_coefficient', '全局聚类系数', ...
        'average_clustering_coefficient', '平均聚类系数', ...
        'local_clustering_coefficients',  '局部聚类系数', ...
        'transitivity',                  '传递性', ...
        'triangles_count',              '三角形数量', ...
        'path_statistics',              '路径统计', ...
        'average_path_length',          '平均路径长度', ...
        'diameter',                     '直径', ...
        'characteristic_path_length',   '特征路径长度', ...
        'efficiency',                   '网络效率', ...
        'shortest_paths_distribution',  '最短路径分布', ...
        'community_statistics',         '社区统计', ...
        'modularity',                   '模块度', ...
        'number_of_communities',        '社区数量', ...
        'community_sizes',              '社区大小', ...
        'community_modularity_scores',  '社区模块度得分', ...
        'community_detection_method',   '社区检测方法', ...
        'community_structure',          '社区结构', ...
        'weight_statistics',            '权重统计', ...
        'weight_distribution',          '权重分布', ...
        'mean_weight',                  '平均权重', ...
        'std_weight',                   '权重标准差', ...
        'max_weight',                   '最大权重', ...
        'min_weight',                   '最小权重', ...
        'weight_skewness',              '权重偏度', ...
        'weight_kurtosis',               '权重峰度', ...
        'assortativity',                '同配性', ...
        'weighted_degree_statistics',   '加权度统计', ...
        'small_world_statistics',       '小世界统计', ...
        'small_worldness',              '小世界性', ...
        'clustering_coefficient_ratio',  '聚类系数比', ...
        'characteristic_path_length_ratio', '特征路径长度比', ...
        'is_small_world',               '是否为小世界网络', ...
        'robustness_statistics',        '鲁棒性统计', ...
        'robustness_to_random_failures', '随机失效鲁棒性', ...
        'robustness_to_targeted_attacks', '针对性攻击鲁棒性', ...
        'largest_component_fraction',    '最大连通分量比例', ...
        'fraction_of_nodes_removed',    '移除节点比例', ...
        'computation_statistics',       '计算统计', ...
        'computation_time_seconds',     '计算时间(秒)', ...
        'memory_usage_mb',              '内存使用量(MB)', ...
        'algorithms_used',               '使用算法', ...
        'status',                       '计算状态' ...
    );
end